#theme: jekyll-theme-minimal
theme: minima
title: Be awesome !!!
email: contact@northwind-traders.com
url: https://northwind-traders.com
description: Bookmark this to keep an eye on my project updates!
